### ISSUE TITLE
kvaudit test panics

### ISSUE THREAD

**Issue by mockturtl** [cznic/kv#34]
I think the update to `lldb` stable in [48b826e](https://github.com/cznic/kv/commit/48b826e72e327d4a217b02b6cec3b706a72d740c#diff-e7db65431402ac8772e210562ddd8300) broke `kvaudit`.

```sh
github.com/cznic/kv/kvaudit (master u=) $ go test .
--- FAIL: TestBad (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e7e56]

goroutine 5 [running]:
panic(0x53fb20, 0xc42000c120)
	/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420090180)
	/usr/lib/go-1.7/src/testing/testing.go:579 +0x25d
panic(0x53fb20, 0xc42000c120)
	/usr/lib/go-1.7/src/runtime/panic.go:458 +0x243
github.com/cznic/lldb.(*SimpleFileFiler).Size(0x0, 0x0, 0x0, 0x0)
	$GOPATH/src/github.com/cznic/lldb/simplefilefiler.go:84 +0x26
github.com/cznic/lldb.(*InnerFiler).Size(0xc420011680, 0xc42009e000, 0x0, 0x816c20)
	$GOPATH/src/github.com/cznic/lldb/filer.go:161 +0x37
github.com/cznic/lldb.NewAllocator(0x804940, 0xc420011680, 0xc420053978, 0x8, 0xc420032038, 0x0)
	$GOPATH/src/github.com/cznic/lldb/falloc.go:328 +0x18c
github.com/cznic/kv/kvaudit.main0(0xc42000c620, 0x10, 0x0, 0x578380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	$GOPATH/src/github.com/cznic/kv/kvaudit/main.go:133 +0x1d6
github.com/cznic/kv/kvaudit.TestBad(0xc420090180)
	$GOPATH/src/github.com/cznic/kv/kvaudit/all_test.go:21 +0xd1
testing.tRunner(0xc420090180, 0x578358)
	/usr/lib/go-1.7/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/lib/go-1.7/src/testing/testing.go:646 +0x2ec
FAIL	github.com/cznic/kv/kvaudit	0.004s
```

If I replace the import in `kvaudit/main.go` with `exp/lldb`, the tests run as expected. 

```sh
# import lldb -> import exp/lldb
github.com/cznic/kv/kvaudit (master * u=) $ go test .
ok  	github.com/cznic/kv/kvaudit	0.002s
```

**Comment by cznic** [comment]
Thanks for the report. Do you want to make the patch?
